version: 1.6.18.{build}
shallow_clone: true
os: Visual Studio 2015

environment:
  matrix:
    - tbs_arch: "x86"
      tbs_tools: "mingw"
      tbs_static_runtime: 1
    
    - tbs_arch: "x64"
      tbs_tools: "mingw"
      tbs_static_runtime: 1
      
      
build_script:
- copy c:\MinGW\bin\mingw32-make.exe c:\MinGW\bin\make.exe
- setx PATH "c:\MinGW\bin";"
#C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1
- make Makefile
        #- C:\mingw64\bin;%PATH%
